// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.1-0.20260318123712-00a90b7a03f4 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xa61MjOZL/VxQ18wF6XX4ATU9zsbFhjAccA8aBTd9tNBwhV6VtbVdJNZLK4O31/36h",
	"R71cMnbPg5sP/c0uSalUKvOXL331AhYnjAKVwjv76iWY4xgkcP2vF6VCAh+EIywX6kMIIuAkkYRR78y7",
	"6N34ESwhQoGZiDgIlvIAEAmBSjIjwNEBCdGMQBQeeg2PqHWJotbwKI7BO/OCbBOv4XH4NSUcQu9M8hQa",
	"nggWEGPDmJTA1er//Yz9f7f9j48H9of/+LXdOO2ss++H//jRa3hylSjqQnJC5956vc6o6ZN1ezcjzpYk",
	"BH5F7Nmrh+v2bnyRQEBmJECJnYsWenLDSzhLgEsCeiWeA5VPEZ5CZP6HIVFkcDSqzNvgqbGx5bUmgCRD",
	"MZbBAmmyAh3MGEdTzCEGiaPD4mxs+i8IpKIzxQKeQhZjJd/Nk5xjAcgMIkVKLiC/sANozpsN9ODBC46T",
	"CJoBix+8w7r81NXNOH4CuqzvMMQxIDbTlAdqWp8u1TFSAdu5LygnEZYzxmNDeIbTSHpn3pd0CkvCpbcp",
	"pgnmc5AoW7V5Jq/hAU1j7+xzmUTOgffo4IBDBEqEJMZzqJ/vNjG3idgSOCch5HvahcgsrGud466sUTk0",
	"rm5GMaZ4DiGarlC3d9O6WiXAxwsyk3UVTMgT0DBhhMo66V/SKXAKEgTqjgYom4ju767RAV5iEuFpBOh5",
	"ARTd9bsX/zzUxojDWxqtMmOsSS1gVLAInlJOXDIDqllFdhq6vxv8ns04YAlPksSOC5qQGITEcWKoljX8",
	"GQtk1iqAUQqDlXaFWIKvie2xNwlfAz8H6DXRGPgSuD8HClztje7vBxeIzBBlEgURASozeIEQLQnWTP+D",
	"hH9Hv6bAVyhHYsSoOQBhtInuBYSIUH1zCkcFwjTUa9U/A7RNZQLGnr0zr3N0DCfvTz/48NPHqd85Co99",
	"fPL+1D85Oj3tnHQ+nLTbbaVOLoD17a93VWzdKTBleAGjMzJ3w9HpiQ80YCGEqJiqjSq7NhwEIEQTjViS",
	"RlqA+mazYSGxTAUiwmhQE/XjRK5QmCoO0Kg/vBgMLxtodHf7aTAe3A71P8bRz93Bdf9CLwfR3OcoidP1",
	"3WV3bqSu0YCIMgTl8rffRGvPi9jJkVIbxdGPHGbemfdDq3DhLeviWhZkxmqqWqLFVT9GL+UcqMzEaSG8",
	"DqRWoF7DK0vUa3ha+l7DM3L1Gt5F/7o/MWP6p/54P+x+6g6uu+fXfQW/r5+w4b34al9/ibkKEYRiIDuP",
	"5rPgpvq5ylplLOOz8jFnuvK1dIL69/r0ytlyUT/FIITTl1ylMaa+EoFGQTsP4SlLpZF+5U72UYg0CX8z",
	"NEZYSGQI/FZ8XJfjts9GPR83HZ+6VQyJn4FlKabTF5xbyVf7a61oJFHKcVQyIq/hCULnaYR58bXwuziI",
	"ffvRF8CXJAA/i92aYRA3CWtli9aFL74mwuE0R3hOqIaeiAipjKPERdX75gM1Itf1pURCLPY0YK+IIDDn",
	"eKX+U3iRTwmew5NkX8AR8E3UZxV/zUCFkerK1Rqk1iheOIg00mHs/uHKDUgcYonru2UjjjisKqTfHR//",
	"Ait/iaMUkCHl2LHGvkkydhhhZhBqsnWxWGjKv/wk0BUTEkIrBxTb4zbN5JtUSDQFlFLyawromcgFMVYm",
	"TZiqISzBATS3OdlvyWKqpqYP97j90oYsBIdOqs/I+NyU67hi590FjErOoqckwhR26q6ZPFJzMw/0zPgX",
	"ayCvLf1vPc0sekUbx9YFVs81thavVhW5G6FJKlH2tzgu3nrYuKTre9hobhpK3TKJ77HO3M5a764R6mmR",
	"paKvra7mrcrjmGM/GWFtEQpSo5UINdPchwy9HrwikBmPmiX3nwnKlTotgQu90ys5R0wo48jO3J6DdprH",
	"7QfvsIlucJLoMFcZC46ilQIzTFGRU2S0ssBZyQlLMiURkSuVPnPygg5ueyN00nxBf9d23GkevPytc3x4",
	"qENm5YiiJYSaNMoqHSqNG4NUMbci2+3doKt02txpiZU7KITSKHTJaaabhlIP0MwMpO0OKe2qarLDUFNX",
	"AjhM46lKJWYoqFEUxU13GseN9wWn6gLmxgkFSfoa1d7oHgWMg0AJcMceShKEkljtcuSiH0PM+MrlXdT3",
	"LVRLqnN6ef7gqV/HR+rXYTUFOr0830Dfjv/x8bNObQ5uzv9zef6fyfnhj67ihJCMOwO5sRnYzdpRO+Pt",
	"fbvtYE6N/zbuXAjZ55w5igt3P/fQh5/aH7SlRARTiUDNVHaQMCqgpkkhSEyinb4TXtShDazmmCuZgREW",
	"mGg2AHdFSUhMA4ds7+8GiMMM9NIClXL6hvUK9TxyTTnx87XuG3UnQ1eTySjLhAKjszlRQuXxkedSXElk",
	"5NKOBeOygRZVYYk0jjFfZYlWwtk0gtjFpBvMq3KxaL5SKa8iZ6RiISjD7oWUiThrtVT0WyrytfRk0SJ0",
	"iSMS+pjP0xioCtR3rKBM+jOW0nD3VBypk698eCFCx5s75ifAYyIUcvohUAJ7bJFSnMqFkkNgU5idBzZO",
	"ZS/SWbFqn8kJZ4FK5qYR+IofuVKYv6daOpNebcqTVQKD4afu9eCie3d5f9MfTrxGMTS8nfx8ez+8KH/r",
	"Xut0t/8/g/FkXB4Y9e9uBmOVIl/0h4N+ZdH9sHs/ueoPJ4Ned1IdGgwn/bth93pjep72Vj6P7m57/fFY",
	"DShik396j5vO0mqosRyXX7wCHLmqLuZ7ZqMqEYxAMppX4GoY5i7e9DBllAQ4MtUba4wlIgU4Lwwn+1Rl",
	"tqFKmWcH7dU+xN1okBehNmK7yi77pMT5Kbdq6x41CHf5YQwBo6G+rADQWAMsN4aa83h82m5v3aIEtVtD",
	"zfEITVMShXlYmFtVyc022832NxczrKrmt2dbV0V8Z8/9zfUOK/JyjcN8ykocWrPzPlhR88jv6htKHnaN",
	"Olyt6+XOxc22G/UQu7RIrao55JbeWBDvymhqzThnYFNKDWsKYMb+kPj4uSAlylFr53dHxSXKOwnvEQ6X",
	"yP1l4mA3T28ZAK9Np5JlRQsc6Nu2veaL3g0acWYtNOXa7KxjnxO5SKfap4dBrGwo0zx3Qp33hLujgQ5R",
	"dbNOxWKl1pet+uk89Q5CdIUl6oZLFfWGWdKJbnSXT0Vf6KDbuzH5adHraz7QBzpR8a/aiQiUYC4zr3VB",
	"lCymqdT0WBpWqF0oavYkmqplOu9UoIjMIFgFUdZrVOseaIATrHNpAgIRGkRpqA6WtaEaKIQIzC9F1Trk",
	"mFEimboZzfIPPyAl7zuYKx4NRmS1kgfqo3fvhjiGs3fvUAXDEjNmxayCCjUlq1GYsTRJmPIiI9sDFmpK",
	"1u1tFO3mjemfDGzr2RcrimMSoIMpFhCqhH+jBiBQ0atkNCsFHBqStwmYE2lavbt+d9JvINMiaOie1IPC",
	"nogEoHKrQgO7CQ4WgI60L6oq4PPzcxPr4Sbj85ZdK1rXg15/OO77ak2RcHiKoUyDMp0clXSy5KYy77du",
	"eCwBihPinXnHzXbzxLo0DY0tnJDWsoOjZIE7rXJJew7SFX3IlFOBMEpqhXIcRYXul5rYJovbMKCmp9ky",
	"8hyEtmjeK9XaS49SPruL3cr+dLU7y4W2FLz1+xPdYC0eoJRK6eUXJzWoqWExflEIjmiO93Yflf5yLR0N",
	"iol5GuDaOsYvppIvyL+hsnv+DuJ925GGxmZr76yjIqfXXMla99tMiq/v8qjdzrARjCfESRJZd9n6lzDx",
	"VcHIHoVM3T7RyLuj97FueCevbm8T4r99Gxum5OFgYGCSW6QiOhDS7N95u/3vN5JTvf/x2+0/yvNpZPPp",
	"dUP54Le8AZNta6MHbkoU2m/bUkimJmXEUH4ez8t9X6Fbqwlztel6+nGHwiEKz3Xfq11v9fFME01K5efM",
	"qSnPisWKBgvOKEvFfz1QDVf5YxluAY/EMYQES4hWut+DcPbgwDpC3UJCl/0JatXamoNw/UAlQwmLosqD",
	"B5WXEApCNLXnqAKiOWOv6Fe8hog987oEC0HmFEL3o7xuf+R3jo8Pm2gwQywmUkLY0Mhpbyp7uaIEe38/",
	"uKi1unDM6FzfW7ZBHepNG8GFfCT0/tDnfY8mbwMhz1m4+qMRzqh29XXiugasnT9n283b3VRbSiQp4OU7",
	"vP7/wutJ++PbcZApgy20IltoVWwcHb3lRYgsxC6eZRYdv7+k1zGQar1G6QFB3fGsG1tC46yusitCVqi6",
	"qJQubfK2OxK+BHlVlCD/pDDuKisP1QR5tQ/XG4K1a4IFBF9KArWbvCbOko80woxAOgoOAwt4Is9CdcqR",
	"XaLx7vnQpldHTqf+QEtevRofPJMoUm6PQ8yWEKIZZ7GRw0pIiBGjQWk73V4DCU43fqFPtNWNu+6omNKq",
	"vsZ3BPYnjuDIHqIQR9VbfEfrk7dHa8okMh20vyIwGiWtPI9xRuM7Ic80kIUxzqJmbIVQVJWIFBuPHp04",
	"+KeZTfstwzYrlO/W9936nNZ3CUXmmumKOyqxL7/cOeAdY0WFu6W13tLY5iGK8i/KTU8U+VqvqOFs6XBq",
	"h+9cm8UXj+v/CwAA//8Dd+dobzYAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
