// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xaYXPittP/Khq1L5L7GwNJLtdLp9MhwCVME8IkcM/TOfIwwl5APVtyJZmEXvnuz0iy",
	"sMEmyfV6N/fi/w5sabWSdn/7211/wgGPE86AKYnPPuGECBKDAmH+taNUKhC9cEDUQj8IQQaCJopyhs9w",
	"p31di2AJEQrsQCRA8lQEgGgITNEZBYEOaIhmFKLwEHuY6nmJluZhRmLAZzhwi2APC/gzpQJCfKZECh6W",
	"wQJioleOyeMVsLlW4/TYwzFl7m/T0wIVCC36/z6Q2l+N2tv7gw+17Ncr9+jw1x+xh9Uq0atKJSib4/V6",
	"7VYxO261rweCL2kI4pJmZ7K96Vb7uiYTCOiMBijJxqKFGezhRPAEhKJgZpI5MDWJyBQi+z8MqRZDosHW",
	"uB2dvJ0lr4wApDiKiQoWyIiV6GDGBZoSATEoEh3me+PTPyBQWs6USJiEPCb63Hd3ck4kIPsSaVFqAZuL",
	"PAB/7ntojOGRxEkEfsDjMT4sn5++0pkgE2DL8gp9EgPiMyO5p4d12VJvI5WwX/tcchIRNeMitoJnJI0U",
	"PsMf0yksqVB495iGRMxBITdrd0/Yw8DSGJ99KIrYaIDvKzQQEIE+QhqTOZT3d5PY20R8CULQEDZrZhOR",
	"nVi2uoq7ypytwuLK7hUTRuYQoukKtdrX9ctVAuJuQWeqbIIJnQALE06ZKov+LZ2CYKBAotagh9xANLq9",
	"QgdkSWhEphGghwUwdNttdX4/NE5KwhsWrZyTlk4t4EzyCCapoFVnBsyoirJhaHTb+5LFBBAFE0Xjigsa",
	"0hikInFipRYt/IFIZOdq4NEGQ7R1hURBzQh7wdo0fAoUK8DQR3cgliBqc2Ag9NpoNOp1EJ0hxhUKIgpM",
	"OXiBEC0pMUr/SsNf0J8piBXaIDTizG6AcuajkYQQUWZuTuOrRISFZq7+ZwHY1y5g/Rmf4ebRMZy8Pn1T",
	"g5/eTmvNo/C4Rk5en9ZOjk5PmyfNNyeNRuMlh6CdKeBsRufVEHN6UgMW8BBClA81juKuggQBSOmjAU/S",
	"yByKuS33WiqiUomotFbho26cqBUKU60BGnT7nV7/wkOD25v3vbveTd/84wK9a/Wuuh0zHaT/kq1oIAiJ",
	"MgHnRwEzfIZ/qOcBsp4Finrmqtdu+NrDjIfW4V4wr2/Grj0bCEuHduvsxt6cQRQqizC2ucPsmaz/W5fp",
	"Atpk4aLfU/vZDpU6koJY0gAmVu7uxu7sW6TfbjnFdSoVmgIauw2Ncb7vu4FfgG53ClVobQ2lvG47FQKY",
	"coaUBaRyWMhMCXu4aEvYw8busIetRWEPd7pX3aF9Z352O1qhZ0/XKjCJQcrKeHKZxoTVtBiDhNk4RKY8",
	"VVbnrZ285ELTJPzH8BgRqZAV8M8xcglCmtX2B4JsyH4ScuI334yx++WfjvGhj95xgZZNz8y4GxgQSZRE",
	"JbEShVRAoKKVZ/mTRg3HbHV4vgO1wWqpUVVLbLWv0WU69dFwAajTvkZpIpUAEuewlECgmYxEhSjq1vzZ",
	"CIlJkujVqEQ37QE68R/RL+i3nyRq+geP/2keH/qV1CBnwR+2PSo/TQc4Bcy63+UUHn6sEUhqbm+W3xum",
	"LAuuJOufsl9rLSOJUkGiArZgD0vK5mlERP4015sEcS17WMuUrTkU8cMg9imvu0nrnOZcUVnBRwZkTpmJ",
	"ABGVSntqQYttYsPgUU0SMoeJ4h+hwr6G+rFmmzPQpFnfh56D9BwtWYBMI0PaK2iffVWSeVXWiiqIXwr8",
	"OOd9RAiyepIIXheC0bYW7k0Fw90hf4xxZQjCl6Qfv8GqtiRRCqggr2Lt0ka+OPHJV7aiXrKozSqfQVbn",
	"w3pwxp2INJK1d15yqSDMrgE5B/PtYBerUkb/TAE9ULWgFjKUzT/0MJmQALRzf7W0dRslzKbv99tS37GT",
	"nfyMh4AsIUuFuddnTSrgTAkeTZKIMHjW7O3ggR57l0CgNXrg4mNWXnhq6v+YYXbSzma3VcglVu5/V4My",
	"ObAjkJGGNKoil96bE6k4gdSlUllKerxrt/00nmqCPkNBSbrMCUfTO/Ze51pTpmBuQSJI0orb2khtD0Yo",
	"4AIkSkBUrIGNpdFYr3JUJT+GmItVFbLo53uk5vG4eXpxbuPx8ZH+dbidWJxenONt627W3t5/MFZ9cH3+",
	"98X538Pzwx9xJUPiopIa3dkXz6t21HC6vW40KpTT7/+ZdiUz1HZg72pzovkOqqyxKwSvSPBv37XRm58a",
	"b5D2g4gSphDokTpEJZxJKNlgCIrQ6FmYg0d9RNaxNzUrxS2v5oFlkwFUV3WkIiyouImRBb5ChW9D1Tdr",
	"WPXzFQzGztJIDx0zJUjwUfMinaKGME3nc8rm/pgVSWYqaE3ADPZquI/tXw6HA0f1A+sMG6GUqeMjXOUR",
	"iqqoyuwWXCgPLbbPVaZxTMTKZRKJ4NMI4iolqxOh0W0PbfbmTnKlT6QgzqRJmn9Sk/saUCaMMxqQaMzs",
	"Cev92XNzOUyv/7511etMWrcXo+tuf4g93L8ZTt7djPo6cWldmVxm0v3f3t3wTmc63dvr3p1OdSadbr9n",
	"sptRvzUaXnb7w167NTRPev1h97bfurIv37d6V63zq675N7i9aXfv7vT/iZ4y/F2b/kuvccenMpZrL6PK",
	"gy6BRFU5s33url3z1QgUZxteX/Kg6tS77Q7Y5t7Z/RaE5ECysJq8MOuDJ1Wukrx6iehq89oUEHYS7a1V",
	"XsLbN3vce53PaFh9vW7L5g4+O23JlCqmKvaRy1TMzW86CHnqstnNZ2Qu2Ry9kWf6Au513hzYJlZ7OgRB",
	"/BwTKrUkKpOGAl8qqWbffSa3qWYeD7koWWQZzS9mMQXJzwp+AX0piPtueEu1Tt8vYVnb7g53vJ8Exjay",
	"vl2nfY0Ggmc+mwrjiEol8qxen1O1SKd+wON6GMTaq5ydVlcEN3201qBn6IRpcOiAWGgXZDm3KYrfQogu",
	"iUKtcKlZSugKOujadEZiYAodtNrXh4Zj5P0Rf8zGzIRUvRKVKCFCOZzvUH1y01QZeTwNt6R1tLRsJ0Zq",
	"pvSmMosiOoNgFUSuP6PnjVlAEjKlEdU+higLojTUG3Olew+FEIH9paVmISzmjCouLC8asx9+MEWoW5hr",
	"HS2iuDLAmNXQq1d9EsPZq1doC9US+y475uEqMUNckdW+S5OECwXhIOubST3Edci8vEW3M/x9VunSozsr",
	"RmIaoIMp0ak0Z7v1NYny/g5nrrh2aEXeJGB3ZGS1b7utYddDtq7qmZq/YTgRDUBz4dwCWwkJFoCO/EbJ",
	"AB8eHnxiXvtczOvZXFm/6rW7/btuTc/JWR/WCjkLcjY5KNhkofJ2hpt+w87mCTCSUHyGj/2Gf5JFNAOk",
	"dZLQ+rJJomRBmvVNuejsE56DqorYKhVMIoKSUgWMRFFu+4XGn2XcOw7kY6OWPc9emJWs2oUiWqHB/6G6",
	"ZKb9z9TMHCHdUzYzvXzTlMqb+YWCXLF7XwKmEnKTR433iG2iQ7aOTleEOR0DoYltp1YtHZNHWw+U9C/Y",
	"Wn2TqL9uVOQCsV0anzUbjacDz9rU+G1KZu7yqNFw2Ag2bpIkibLgWv9D2rJ3rsgLSoSmLmqQ95nK49rD",
	"J08un6UR//k8NWyKWqFAjy1JREOkIwpIg+Wvv+36OvyRyJg8CJtimhiXZWPukIr+omMimW9Vu/H92sMJ",
	"r6o+t007WHshg4dy5DGBZ7vdbtsD7r2DdB1XiFyxYCE446n8ecyMs27a6yJzdxrHEFKiIFqZQiIirp2Z",
	"hQGTN6OL7hDVS9X6XrgeM8VRwqNoq52qOTllIKXNDLfhwO6xnVf3nsKDtu1HEynpnEFY/XlPqzuoNY+P",
	"D33UmyEeU6UgtF2Z7KZcr1sf7GjU65RqqCTmbG7uLW/D7AKd7QJW+T0N8Tf5UOjesimQ6pyHq3/b763J",
	"b3//tC7BTfPrLLt767vmzKiipgn4HYDOSePtt1vfHQWJtFOtEDxSaTvdJ0dH306NEZOOduWfN3Hhuo3f",
	"JRZboMmwtNCvKcPx2ttDl4pQZ9E6gqpKSi+zT7mh0oY3uVUtSG9e7YIzqsTmMSuA8zbMP9Ao0uglIOZL",
	"CNFM8Nji3UoqiBFnQWE5U9MFBZVo3DE72ovGVZeTD6lvf55ZwU5OKmJcton8OLad++TbOxfjCs14ysLv",
	"0o7tFeXWtI9SPMnrlTFARWgkrWnmRaLsEPLEkCq5851HmdRfgPpqRtP4ljEmO5T/2l6l7V1ATj7dSe2F",
	"0MWmNP6sKS62quVZ9eP5VPIC1GVe9f5KRnPpKq57i0VUIlci3z6urKIeLCD4WDgnVzC233qb064iu7ec",
	"54WsuvGMTMI+DM2rPGhzULL0Ybs27j21f6Np5VxXd75f/38AAAD//2Yx19GiLwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
