// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xa8XPauLP/VzS6+yHp1xhI0vSam5sbAjRhLiFMQvreTcljhL2Arrbkk2QSrsf//kaS",
	"hQ02IW1fO/3h/Qa2tFqtdj/72ZU/4YDHCWfAlMRnn3BCBIlBgTD/2lEqFYheOCBqrh+EIANBE0U5w2e4",
	"076uRbCACAV2IBIgeSoCQDQEpuiUgkAHNERTClF4iD1M9bxES/MwIzHgMxy4RbCHBfydUgEhPlMiBQ/L",
	"YA4x0SvH5OkK2EyrcXrs4Zgy97fpaYEKhBb9Px9I7Z9G7e3DwYda9uuVe3T4+8/Yw2qZ6FWlEpTN8Gq1",
	"cquYHbfa1wPBFzQEcUkzm2xuutW+rskEAjqlAUqysWhuBns4ETwBoSiYmWQGTI0jMoHI/g9DqsWQaLAx",
	"bksnb2vJKyMAKY5iooI5MmIlOphygSZEQAyKRIf53vjkLwiUljMhEsYhj4m2+/ZOzokEZF8iLUrNYX2Q",
	"B+DPfA+NMDyROInAD3g8wodl++kjnQoyBrYor9AnMSA+NZJ7eliXLfQ2Ugm7tc8lJxFRUy5iK3hK0kjh",
	"M/wxncCCCoW3zTQkYgYKuVnbe8IeBpbG+OxDUcRaA/xQoYGACLQJaUxmUN7fTWJPE/EFCEFDWK+ZTUR2",
	"YtnrKs4qC7YKjyuHV0wYmUGIJkvUal/XL5cJiLs5naqyCyZ0DCxMOGWqLPqPdAKCgQKJWoMecgPR/e0V",
	"OiALQiMyiQA9zoGh226r8+ehCVIS3rBo6YK0ZLWAM8kjGKeCVtkMmFEVZcPQ/W3vaxYTQBSMFY0rDmhI",
	"Y5CKxImVWvTwRyKRnauBRzsM0d4VEgU1I+wFa9PwOVCsAEMf3YFYgKjNgIHQa6P7+14H0SliXKEgosCU",
	"gxcI0YISo/TvNPwN/Z2CWKI1QiPO7AYoZz66lxAiyszJaXyViLDQzNX/LAD7OgRsPOMz3Dw6hpPXp29q",
	"8MvbSa15FB7XyMnr09rJ0elp86T55qTRaOAytj4DrXvtpeMu4GxKZ9VodHpSAxbwEEKUDzUx5U6NBAFI",
	"6aMBT9LI2M8crHstFVGpRFRaB/JRN07UEoWp1gANuv1Or3/hocHtzfveXe+mb/5xgd61elfdjpkO0n/J",
	"VjRmhESZ3PSzgCk+wz/V81xaz3JKPYvqazd85WHGQxubL5jXN2NXns2ZJaPdOhezh2zAh8oi4q2PO3sm",
	"6y88970WcLlvPHeJ8rn9bGZVnXRBLGgAYyt3e2N39i3Sbzfi5zqVCk0AjdyGRjjf993AL6C8s0IVsFtH",
	"Ka/bToUAppwjZbmrnEEyV8IeLvoS9rDxO+xh61HYw53uVXdo35mf3Y5WaK91rQLjGKSsTD2XaUxYTYsx",
	"oJmNQ2TCU2V13tjJSw40TcIvRtKISIWsgC+H0wUIaVbbnTOyIbv5yonffDPC7pd/OsKHPnrHBVo0PTPj",
	"bmBAJFESlcRKFFIBgYqWnqVaGjUcCdaZ/A7UGtalBmAtsdW+RpfpxEfDOaBO+xqliVQCSJzDUgKBJj0S",
	"FRKuW/NXIyQmSaJXoxLdtAfoxH9Cv6E/fpGo6R88/ad5fOhXsoicMH/YjKjcmg5wCpj1sE0/PPxUI5DU",
	"3N5sKWCAXxZCSdY/Zb9WWkYSpYJEBWzBHpaUzdKIiPxprjcJ4lr2sJYpW3Mo4odB7FNed5NWOSO6orKC",
	"ugzIjDKTASIqlY7UghabHIjBkxonZAZjxT9ChX8N9WNNTKeg+bU+Dz0H6TlasgCZRobfVzBE+6ok86qs",
	"FVUQvxT4cU4RiRBk+SxnvC4ko00t3JsKMrzFExnjynCJr6lU/oBlbUGiFFBBXsXapY18dY2Ur2xFvWRR",
	"W4DuQVYXw3pwRrOINJJ1dF5yqSDMjgG5APPtYJerUkb/TgE9UjWnFjKULVX0MJmQAHRwf7MKdxMlzKYf",
	"dvtS37GTrVKOh4AsIUuFOde9LhVwpgSPxklEGOx1ezt4oMfeJRBojR65+Jh1Ip6b+l9mmJ20tdlNFXKJ",
	"lfvf1qBMDuwIZKQhjarIdQKMRSoskLqqK6tej7f9tp/GE83lpygoSZc54Wh6x97rXGvKFMwsSARJWnFa",
	"a6ntwT0KuACJEhAVa2DjaTTWqxxVyY8h5mJZhSz6+Q6peT5unl6c23x8fKR/HW7WIKcX51s1RrP29uGD",
	"8eqD6/N/L87/HZ4f/owrGRIXldTozr7Yr9pRw+n2utGoUE6//zLtSm6o/cCe1dqi+Q6qvLErBK/oBdy+",
	"a6M3vzTeIB0HESVMIdAjdYpKOJNQ8sEQFKHRXpiDJ20iG9jr9pbillfzwLLJAKobQFIRFlScxL0FvkIz",
	"cE3V12tY9fMVDMZO00gPHTElSPBR8yJdzYYwSWczymb+iBVJZipoTcAUdmq4i+1fDocDR/UDGwxroZSp",
	"4yNcFRGKqqjK7eZcKA/NN+0q0zgmYukqiUTwSQRxlZLVhdD9bQ+t9+YsudQWKYgzZZLmn9TUvgaUCeOM",
	"BiQaMWthvT9rN1fD9PrvW1e9zrh1e3F/3e0PsYf7N8Pxu5v7vi5cWlemlhl3/7t3N7zTlU739rp3p0ud",
	"cafb75nq5r7fuh9edvvDXrs1NE96/WH3tt+6si/ft3pXrfOrrvk3uL1pd+/u9P+xnjL8U7v+S49xK6Yy",
	"lmsPoyqCLoFEVTWzfe6OXfPVCBRna15fiqDq0rvtDGxr7+x8C0JyIJlbTV5Y9cGzKldJXr5EdLV7rRsI",
	"W4X2xiov4e3rPe48zj0aVh+v27I5g88uWzKliqWKfeQqFXPy68uGvHRZ7+YzKpdsjt7InisE9zq/R9gk",
	"VjsuE4J4HxMq3V5UFg0FvlRSzb77TG5TzTwec1GyyDKaX81iCpL3Cn4BfSmI+2F4S7VOPy5hWdmLIO54",
	"PwmMb2RXfJ32NRoInsVsKkwgKpXIs3p9RtU8nfgBj+thEOuocn5a3RFcX7m1Bj1DJ8xdiE6IhZuFrOY2",
	"/fNbCNElUagVLjRLCV1DB12bS5QYmEIHrfb1oeEY+VWKP2IjZlKqXolKlBChHM53qLbcJFVGHk/DDWkd",
	"LS3biZGaKb3uzKKITiFYBpG7ytHzRiwgCZnQiOoYQ5QFURrqjbkuv4dCiMD+0lKzFBZzRhUXlheN2E8/",
	"mSbULcy0jhZRXBtgxGro1as+ieHs1Su0gWqJfZeZebhMzBDXZLXv0iThQkE4yK7YpB7iLtO8/DZva/j7",
	"rNOlR3eWjMQ0QAcToktpzrb7axLlV0GcuebaoRV5k4DdkZHVvu22hl0P2b6qZ3r+huFENADNhXMPbCUk",
	"mAM68hslB3x8fPSJee1zMatnc2X9qtfu9u+6NT0nZ31YK+Q8yPnkoOCThc7bGW76DTubJ8BIQvEZPvYb",
	"/kmW0QyQ1klC64smiZI5adbX7aKzT3gGqipjq1QwiQhKSh0wEkW57xfuCC3j3gogHxu1rD17Ydayahea",
	"aIVvAT5Ut8x0/JmemSOkO9pm5trf3F/l9/6Fhlzxor8ETCXkJk8a7xFbZ4dsHV2uCGMdA6GJvXmtWjom",
	"T7YfKOk/sLH6ulB/3aioBWK7ND5rNhrPJ56V6fHbksyc5VGj4bARbN4kSRJlybX+l7Rt71yRF7QITV/U",
	"IO+ezuPKwyfPLp+VEf/5PDVsiVqhQI8tSERDpDMKSIPlr7/v+jr9kci4PAhbYpocl1VjzkjFeNE5kcw2",
	"ut34YeXhhFd1n9vm5lhHIYPHcuYxiWfzZt5eD7j3DtJ1XiFyyYK54Iyn8tcRM8G6vokXWbjTOIaQEgXR",
	"0jQSEXHXmVkaMHUzuugOUb3Ure+FqxFTHCU8ijauUzUnpwyktJXhJhzYPbbz7t5zeNC2V9dESjpjEFZ/",
	"CdTqDmrN4+NDH/WmiMdUKQjtrUx2Uu5aXBv2/r7XKfVQSczZzJxbfg2zDXT2FrAq7mmIv/Sbope3Wx8s",
	"lQKpznm4/L8Oeuvvm99JrUpY0/w2y24f+bYvM6qouQH8ARDnpPH2+63vTEEiHVFLBE9U2mvuk6Oj76fG",
	"PZOOc+WfQXHhrhp/SCC2KJMBaeGypozFK28HVyrinIXqCKraKL3MP+WaRxvS5Fa1CL1+tY3MqBKYR6yA",
	"zJsY/0ijSEOXgJgvIERTwWMLdkupIEacBYXlTEMXFFRCccfsaCcUVx1OPqS++RlnBTU5qUhw2SZyc2wG",
	"98n3Dy7GFZrylIU/pB/bI8q9aRefeJbUK+OAitBIWtfMO0SZEfKqkCq59ZFHmdFfgPpmTtP4njkmM8r/",
	"+16l711AzjydpXZC6HzdF9/rivONVnnW+thfR16Ausxb3t/IaS5du3Vnp4hK5Prjm+bK2unBHIKPBTu5",
	"brH9JtxYu4rp3nKed7HqJjIyCbswNG/xoLWhZOkDeO3cOxr/RtPKua7p/LD63wAAAP//Xt8S9MovAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
