// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package v1alpha1

import (
	"time"
)

// Defines values for ACMProviderHintsPlatform.
const (
	Baremetal ACMProviderHintsPlatform = "baremetal"
	Kubevirt  ACMProviderHintsPlatform = "kubevirt"
)

// Defines values for ClusterServiceType.
const (
	ClusterServiceTypeCluster ClusterServiceType = "cluster"
)

// Defines values for ClusterStatus.
const (
	DELETED      ClusterStatus = "DELETED"
	DELETING     ClusterStatus = "DELETING"
	FAILED       ClusterStatus = "FAILED"
	PENDING      ClusterStatus = "PENDING"
	PROVISIONING ClusterStatus = "PROVISIONING"
	READY        ClusterStatus = "READY"
)

// Defines values for ControlPlaneSpecCount.
const (
	N1 ControlPlaneSpecCount = 1
	N3 ControlPlaneSpecCount = 3
	N5 ControlPlaneSpecCount = 5
)

// Defines values for ErrorType.
const (
	ALREADYEXISTS       ErrorType = "ALREADY_EXISTS"
	INTERNAL            ErrorType = "INTERNAL"
	INVALIDARGUMENT     ErrorType = "INVALID_ARGUMENT"
	NOTFOUND            ErrorType = "NOT_FOUND"
	PERMISSIONDENIED    ErrorType = "PERMISSION_DENIED"
	UNAUTHENTICATED     ErrorType = "UNAUTHENTICATED"
	UNAVAILABLE         ErrorType = "UNAVAILABLE"
	UNPROCESSABLEENTITY ErrorType = "UNPROCESSABLE_ENTITY"
)

// ACMProviderHints ACM-specific provider hints
type ACMProviderHints struct {
	// AgentLabels Labels to match agents (for baremetal)
	AgentLabels *map[string]string `json:"agent_labels,omitempty"`

	// BaseDomain Base domain for the cluster (e.g., "example.com")
	BaseDomain *string `json:"base_domain,omitempty"`

	// InfraEnv Name of the InfraEnv to use (for baremetal)
	InfraEnv *string `json:"infra_env,omitempty"`

	// Platform Target platform for the cluster
	Platform *ACMProviderHintsPlatform `json:"platform,omitempty"`

	// ReleaseImage Optional override for the release image
	ReleaseImage *string `json:"release_image,omitempty"`
}

// ACMProviderHintsPlatform Target platform for the cluster
type ACMProviderHintsPlatform string

// Cluster A cluster resource managed by ACM/HyperShift
type Cluster struct {
	// ApiEndpoint Kubernetes API endpoint URL (available when READY)
	ApiEndpoint *string `json:"api_endpoint,omitempty"`

	// ConsoleUri OpenShift console URI (available when READY)
	ConsoleUri *string `json:"console_uri,omitempty"`

	// CreateTime Timestamp when the cluster was created
	CreateTime *time.Time `json:"create_time,omitempty"`

	// Kubeconfig Base64-encoded kubeconfig for cluster access. Populated when cluster status is READY. Empty during PENDING, PROVISIONING, or FAILED states.
	Kubeconfig *string `json:"kubeconfig,omitempty"`

	// Metadata Metadata for the cluster
	Metadata ClusterMetadata `json:"metadata"`

	// Nodes Node configuration for the cluster
	Nodes ClusterNodes `json:"nodes"`

	// Path Resource path for this cluster
	Path *string `json:"path,omitempty"`

	// ProviderHints Provider-specific configuration hints
	ProviderHints *ProviderHints `json:"provider_hints,omitempty"`

	// ServiceType Service type identifier. Must be "cluster" for this SP.
	ServiceType ClusterServiceType `json:"service_type"`

	// Status Current status of the cluster
	Status *ClusterStatus `json:"status,omitempty"`

	// StatusMessage Human-readable message about the current status
	StatusMessage *string `json:"status_message,omitempty"`

	// UpdateTime Timestamp when the cluster was last updated
	UpdateTime *time.Time `json:"update_time,omitempty"`

	// Version OpenShift version for the cluster (e.g., "4.17", "4.17.6"). For v1, the SP accepts OpenShift versions directly, matching ClusterImageSet resources on the ACM Hub. The DCM upstream cluster spec uses Kubernetes versions; the mapping is OCP 4.x = K8s 1.(x+13).
	Version string `json:"version"`
}

// ClusterServiceType Service type identifier. Must be "cluster" for this SP.
type ClusterServiceType string

// ClusterStatus Current status of the cluster
type ClusterStatus string

// ClusterList Paginated list of clusters
type ClusterList struct {
	// NextPageToken Token to fetch the next page of results
	NextPageToken *string `json:"next_page_token,omitempty"`

	// Results List of clusters
	Results *[]Cluster `json:"results,omitempty"`
}

// ClusterMetadata Metadata for the cluster
type ClusterMetadata struct {
	// Annotations Key-value annotations for the cluster
	Annotations *map[string]string `json:"annotations,omitempty"`

	// Labels Key-value labels for the cluster
	Labels *map[string]string `json:"labels,omitempty"`

	// Name Cluster resource name. Used as the canonical cluster identifier.
	Name string `json:"name"`
}

// ClusterNodes Node configuration for the cluster
type ClusterNodes struct {
	// ControlPlane Control plane node specification
	ControlPlane ControlPlaneSpec `json:"control_plane"`

	// Workers Worker node specification
	Workers WorkerSpec `json:"workers"`
}

// ControlPlaneSpec Control plane node specification
type ControlPlaneSpec struct {
	// Count Number of control plane nodes
	Count ControlPlaneSpecCount `json:"count"`

	// Cpu Number of CPU cores per control plane node
	Cpu int `json:"cpu"`

	// Memory Memory per control plane node (e.g., "16GB", "32GB")
	Memory string `json:"memory"`

	// Storage Storage per control plane node (e.g., "120GB", "500GB")
	Storage string `json:"storage"`
}

// ControlPlaneSpecCount Number of control plane nodes
type ControlPlaneSpecCount int

// Error RFC 7807 compliant error response
type Error struct {
	// Detail Human-readable explanation specific to this occurrence
	Detail *string `json:"detail,omitempty"`

	// Instance Unique identifier for this specific error occurrence. Useful for
	// tracking and debugging.
	Instance *string `json:"instance,omitempty"`

	// Status HTTP status code
	Status *int32 `json:"status,omitempty"`

	// Title Short, human-readable summary of the problem
	Title string `json:"title"`

	// Type URI reference identifying the problem type. This is the canonical
	// error code.
	Type ErrorType `json:"type"`
}

// ErrorType URI reference identifying the problem type. This is the canonical
// error code.
type ErrorType string

// Health Health status singleton resource
type Health struct {
	// Path Canonical path of the resource
	Path *string `json:"path,omitempty"`

	// State Health state
	State *string `json:"state,omitempty"`

	// Type Resource type identifier
	Type *string `json:"type,omitempty"`
}

// ProviderHints Provider-specific configuration hints
type ProviderHints struct {
	// Acm ACM-specific provider hints
	Acm *ACMProviderHints `json:"acm,omitempty"`
}

// WorkerSpec Worker node specification
type WorkerSpec struct {
	// Count Number of worker nodes
	Count int `json:"count"`

	// Cpu Number of CPU cores per worker node
	Cpu int `json:"cpu"`

	// Memory Memory per worker node (e.g., "16GB", "32GB")
	Memory string `json:"memory"`

	// Storage Storage per worker node (e.g., "120GB", "500GB")
	Storage string `json:"storage"`
}

// ClusterIdPath defines model for ClusterIdPath.
type ClusterIdPath = string

// ListClustersParams defines parameters for ListClusters.
type ListClustersParams struct {
	// PageToken Token for fetching the next page of results
	PageToken *string `form:"page_token,omitempty" json:"page_token,omitempty"`

	// MaxPageSize Maximum number of results to return per page
	MaxPageSize *int32 `form:"max_page_size,omitempty" json:"max_page_size,omitempty"`
}

// CreateClusterJSONRequestBody defines body for CreateCluster for application/json ContentType.
type CreateClusterJSONRequestBody = Cluster
