name: Secret Scan

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  schedule:
    - cron: "17 4 * * 1"
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  gitleaks-diff:
    if: github.event_name == 'pull_request'
    uses: dcm-project/shared-workflows/.github/workflows/gitleaks.yaml@6087a10490802f344d39e7327a1bfe61f3a1e3b3
    with:
      scan-mode: diff
      base-sha: ${{ github.event.pull_request.base.sha }}
      head-sha: ${{ github.event.pull_request.head.sha }}
      go-version-file: go.mod

  gitleaks-push:
    if: github.event_name == 'push'
    uses: dcm-project/shared-workflows/.github/workflows/gitleaks.yaml@6087a10490802f344d39e7327a1bfe61f3a1e3b3
    with:
      scan-mode: push
      base-sha: ${{ github.event.before }}
      head-sha: ${{ github.sha }}
      go-version-file: go.mod

  gitleaks-full-history:
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    uses: dcm-project/shared-workflows/.github/workflows/gitleaks.yaml@6087a10490802f344d39e7327a1bfe61f3a1e3b3
    with:
      scan-mode: full
      go-version-file: go.mod
